name: umx-gpu

channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python=3.8
  - numpy=1.18
  - scipy=1.4
  - pytorch==1.10.2
  - torchaudio==0.10.2
  - cudatoolkit=11.1
  - scikit-learn=0.22
  - tqdm
  - libsndfile
  - ffmpeg
  - pip
  - pip:
      - musdb==0.3.1
      - museval==0.3.1
      - asteroid-filterbanks>=0.3.2
      - gitpython
